# -*- coding: utf-8 -*-
"""assignment5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hz6_V2mtOvhvm2RCm3GFJ2cO_pqvyJZ8
"""

#1.1. What does an empty dictionary code look like?
------>

    dict{}

#2. What is the value of a dictionary value with the key foo and the value 42?
-------->

   dict{foo:42}

#3. What is the most significant distinction between a dictionary and a list?

--------->

  Difference between dict and list is that user can create dict by unordered term but in list data will be in orderd term.
  In dict data will be always in key:value combination but not in the list.

#4. What happens if you try to access spam[foo] if spam is {bar : 100}?
-------->

  It will give you keyerror.

#5. If a dictionary is stored in spam, what is the difference between the expressions cat in spam and cat in spam.keys()?
-------->
   
   when we call 'cat'it will cheak whether the 'cat' is key or value in the dict.and when we call spam.keys() then 
   it will cheak that there is any key called 'cat'. so nearly its same.

#6. If a dictionary is stored in spam, what is the difference between the expressions cat in spam and cat in spam.values()?

-------->
   
   when we call 'cat'it will cheak whether it contain 'cat' as a value or key in dict and when we call spam.values() then 
   we are cheaking that is there any value called 'cat'.

#7. What is a shortcut for the following code?

 if color not in spam:
 spam[color] =black
 ------->
  it will be:
  spam.setdefault('colour','black')

#8. How do you pretty print dictionary values using which module and function?
#--------->
pprint.pprint()